Add models #41
nadcock/CSC478-SOC-Game pull request #43
Opened 2017-10-23 22:41 UTC by nadcock

## Added API Calls:
### None

## Modified API Calls:
- ### /api/game/createGame
   - Returns a list of players currently attached to the game
   - **Required Parameters**: "game_id" *(String)* **ADDED: "game_name": String
   - Returns a game object with "game_id" *(String)*  and "game_name" *(String)*, and a player object with "player_id" *(String)* and "player_name" *(String)* "settlement_id"s *(String)* **ADDED: player_age *(Int)***
   - Example return: 
```javascript 
                       { "Players":  [ 
                               { "player":  {
                                      "player_id": "XF093D", 
                                      "player_name": "Nick",
                                      "player_age": "32",
                                      "owned_settlements": "(s4,5) (s5,7) (s2,7) (s2,6)",
                                      "player_color": "white"
                                },
                                { "player":  {
                                      "player_id": "IIZ892", 
                                      "player_name": "Tom",
                                      "player_age": "30",
                                      "owned_settlements": "(s2,4)",
                                      "player_color": "blue"
                                },
                                { "player":  {
                                      "player_id": "3FD745", 
                                      "player_name": "Another",
                                      "player_age": "43",
                                      "owned_settlements": "(s6,2) (s3,7)"
                                      "player_color": "orange"
                                },
                       ]}
```
- ### /api/game/getPlayersInGame
   - Returns a list of players currently attached to the game
   - **ADDED: Now sets player name to "player_name" parameter when creating player**
   - **Required Parameters**: "game_id" *(String)* 
   - Returns a Players object with an array of player objects each with "player_id" *(String)* and "player_name" *(String)* "settlement_id"s*(String)* *"player_color" *(String)* **ADDED: player_age *(Int)***
   - Example return: 
```javascript 
                       { "Players":  [ 
                               { "player":  {
                                      "player_id": "XF093D", 
                                      "player_name": "Nick",
                                      "player_age": "32",
                                      "owned_settlements": "(s4,5) (s5,7) (s2,7) (s2,6)",
                                      "player_color": "white"
                                },
                                { "player":  {
                                      "player_id": "IIZ892", 
                                      "player_name": "Tom",
                                      "player_age": "30",
                                      "owned_settlements": "(s2,4)",
                                      "player_color": "blue"
                                },
                                { "player":  {
                                      "player_id": "3FD745", 
                                      "player_name": "Another",
                                      "player_age": "43",
                                      "owned_settlements": "(s6,2) (s3,7)"
                                      "player_color": "orange"
                                },
                       ]}
```

## Other Changes:
 Added error handling for api calls. Now an error will be returned if a call is missing a required parameter, or if the specified parameter is invalid.

2017-10-24 19:50 UTC, mpolsgrove approved these changes

2017-10-25 02:45 UTC, davmmeyer requested changes

2017-10-25 02:45 UTC, davmmeyer commented on cos/models/Board.py
> +class Board(object):
Please add an in code comment to how this algorithm functions. Roger will likely be very interested in the gameboard setup.

2017-10-25 02:45 UTC, davmmeyer commented on cos/views/views.py
> +        game_id = json_body['game_id']
The game_id variable looks like it would lose scope outside of the IF block. Is that not the case?

2017-10-25 02:45 UTC, davmmeyer commented on cos/views/views.py
> +    if game_id not in request.registry.games.games:
This appears to be a copy/paste duplicate of the IF block above it.

2017-10-25 17:35 UTC, nadcock commented on cos/views/views.py
> +        game_id = json_body['game_id']
Python has an interesting quirk where unlike a lot of languages, variables created in if blocks (and some loops) are still considered local to the function, not just the block. See here: https://stackoverflow.com/questions/2829528/whats-the-scope-of-a-variable-initialized-in-an-if-statement

2017-10-25 18:13 UTC, nadcock commented on cos/models/Board.py
> +class Board(object):
fixed

2017-10-25 18:15 UTC, nadcock commented
@davmmeyer please re-review and accept if everything looks good.

2017-10-25 18:24 UTC, nadcock commented on cos/views/views.py
> +    if game_id not in request.registry.games.games:
fixed

2017-10-28 22:22 UTC, davmmeyer approved these changes

2017-10-28 22:23 UTC, merged